### PR TITLE
Expose INDCPA-KYBER primitives

### PR DESCRIPTION
**Pull request by tbrezot**
This MR exposes the INDCPA-KYBER primitives:
- the functional modifications are done in the first commit;
- the second commit enforces the Unix encoding on the modified files.

### CODE REVIEW

**Comment by mberry** [comment]
Hey, thanks for the PR. 

Exposed inner api functionality did actually exist recently to run the test vectors. That was replaced with rust config flags.

I'm fine to expose them, but my main concern with this merge is the sheer number of lines due to the formatting changes, would it be possible to separate out exposing the primitives and formatting into different PR's? 

I hear you on the rustfmt matter and it's certainly an outstanding matter to fix, more likely integrate it into CI.

Also would prefer to name the feature `hazmat` if that's ok, `indcpa` implies security, whereas hazmat is commonly used to indicate dangerous api's. 

Thanks again.

**Comment by tbrezot** [comment]
Hey, I removed the formatting changes and renamed the feature to `hazmat`. I didn't know this practice, thanks for the explanation.

Is it good for you now ?

**Comment by mberry** [comment]
Looks great Théophile, thanks. I will merge sometime tomorrow Sydney time and get the crate updated. Cheers.

**Comment by tbrezot** [comment]
Great, thanks a lot!

**Pull request merged**
